server:
  port: 56565


wifi:
# 连接的wifi名
  name: "海大校园网"
#  账号
  username: "123"
#  密码
  password: "123"

logging:
  file:
    name: ./cwac/application.log
  pattern:
    file: "%d{MM-dd HH:mm:ss} %-5level : %m%n"
